### ISSUE TITLE
Where does User.Name come from?

### ISSUE THREAD

**Issue by suganoo** [sausheong/gwp#14]
hi, sau sheong chang.

I could not make sense where `{{ User.Name }}` comes from. Where does it come from?
https://github.com/sausheong/gwp/blob/master/Chapter_2_Go_ChitChat/chitchat/templates/index.html#L12

Supposingly it is binding Thread.UserId and User.Id. but I could not find out where it is binding them.

**Comment by anson-vandoren** [comment]
Hi @suganoo, I had a similar question when I first looked at the code, and found the answer eventually:

In [route_main.go](https://github.com/sausheong/gwp/blob/master/Chapter_2_Go_ChitChat/chitchat/route_main.go#L21) we are calling `Threads()` which gets all threads from the database and returns them. This is what's passed into the "index" template, and is referred to in the index.html file by the "." notation. The `{{ range . }}` directive iterates over each thread we pass in, so the `{{ .User.Name }}` directive is calling a method on each thread. You can see this method in [thread.go](https://github.com/sausheong/gwp/blob/master/Chapter_2_Go_ChitChat/chitchat/data/thread.go#L117):

```golang
// Get the user who started this thread
func (thread *Thread) User() (user User) {
	user = User{}
	Db.QueryRow("SELECT id, uuid, name, email, created_at FROM users WHERE id = $1", thread.UserId).
		Scan(&user.Id, &user.Uuid, &user.Name, &user.Email, &user.CreatedAt)
	return
}
```

The `User()` method returns a `User` struct, which has a member called `Name`

It was a little confusing to me at first because I didn't realize the "." notation in a template could either refer to a variable or method.

Hope that helps

**Comment by suganoo** [comment]
It took me over ten minutes to remind me what kind of issue it was I opened.
I forgot it totally , hahaha.

Ah, I understood `User` struct has `Name`.
https://github.com/sausheong/gwp/blob/master/Chapter_2_Go_ChitChat/chitchat/data/user.go#L10

Thank you so much !
